[theme]
primaryColor = "#3498DB"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#0d1117"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
